######################################################################
# Automatically generated by qmake (2.01a) mer gen 13 18:03:59 2010
######################################################################

CONFIG += qtestlib
QT += network
TEMPLATE = app
TARGET = test-tileprovider
DEPENDPATH += ../../src/
INCLUDEPATH += ../../src/

# Input
SOURCES += testtileprovider.cpp
SOURCES += ../../src/tileprovider.cpp
HEADERS += ../../src/tileprovider.h
